version: "3.4"
services:
  website17:
    image: ruby:3.4.7
    container_name: website17
    ports:
      - '4567:4567'
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    working_dir: /app
