services:
  website17:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_NAME: user
        USER_UID: 1000
        USER_GID: 1000
    group_add:
      - "${DOCKER_GID:-1001}"
    env_file:
      - ../website.env
    ports:
      - '4567:4567'
    volumes:
      - ..:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/user/.ssh
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    command: sleep infinity
    user: user
    stdin_open: true
    tty: true
    networks:
      - local-kleer-network

networks:
  local-kleer-network:
    external: true
